import type {Metadata} from "next";
import {Frank_Ruhl_Libre} from "next/font/google";
import "./globals.css";
import {ContextProvider} from "@/app/context";

const fr = Frank_Ruhl_Libre({
    subsets: ["hebrew"]
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ContextProvider>
            <html lang="en">
            <body
                style={{direction: "rtl"}}
                className={`${fr.className} antialiased body`}
            >

            {children}
            </body>
            </html>
        </ContextProvider>
    );
}
